### PR TITLE
feat(chai-to-assert): support expect().to.be

### PR DESCRIPTION
**Pull request by popomore**

### CODE REVIEW

**Comment by popomore** [comment]
ping @twada

**Comment by twada** [comment]
@popomore Thanks! And I'm so sorry that I do not have enough time now so I'll work on your PRs this weekend.

**Comment by popomore** [comment]
@twada OK

**Comment by popomore** [comment]
@twada Any time to review this PR?

**Comment by twada** [comment]
@popomore Thank you for your PR, and I'm so sorry for my late response.

When I reviewed your PR, I also found that `expect().to.be` is not a chai's matcher, but `expect.js`'s.
I prefer "Do One Thing and Do It Well" design so I've started developing [expect-js-to-assert](https://github.com/twada/expect-js-to-assert).

There remains [much room for improvement](https://github.com/twada/expect-js-to-assert#features) so would you give me PR there?

**Comment by popomore** [comment]
@twada I think the API of chai is quite same as should/expect, so it's good to use one repo for compatible all API. If you seperate two repo to maintain, it will contain many same code, and always fix the two repo when facing issue.

**Comment by twada** [comment]
@popomore Thank you for your opinion and discussion.

> I think the API of chai is quite same as should/expect

should.js looks similar to chai (looks like subset of chai) but not identical, and in fact, their taste differs more than we think.
They provide matchers in same name, but their behavior differs more than we think.

- chai aims to assert as much as possible, bloating APIs, handling complex subject such as object-like-objects, Map/Set, ...
- expect.js seems to be staying simple and conservative


> If you seperate two repo to maintain, it will contain many same code, and always fix the two repo when facing issue.

When duplication makes us annoying, we can make the third common module for that.

If I create expect.js feature in `chai-to-assert`

- It's difficult to know such feature from module name ( `chai-to-assert`)
- When I extract expect.js feature out to new module, it's a breaking change, causing major update and formal announcement


Making breaking change is a bigger problem than temporal duplication.


Thanks.

**Comment by popomore** [comment]
Thank you for discussion, it make sense to me.

Do you have implemented these two feature in expect-js-to-assert?

**Comment by twada** [comment]
@popomore Thank you for the discussion.

> Do you have implement these two feature in expect-js-to-assert?

`be()` is implemented but `.throw()` is not.
I can implement it in a few days but PRs are always welcome ;-)

**Comment by popomore** [comment]
I made a PR https://github.com/twada/expect-js-to-assert/pull/2

**Pull request closed without merging**
